Introduce dummy defaults for ScoreType and RegularizerType to workaround bug in C# protogen messages.cs(353,63): error CS0117: 'Artm.RegularizerType' does not contain a definition for 'RegularizerType_SmoothSparseTheta'